env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    - task update-version-file

dist: build

archives:
  - format_overrides:
      - goos: windows
        format: zip

builds:
  - main: ./cmd/svt
    binary: 'svt'
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.build={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    targets:
      - linux_amd64
      - darwin_arm64
      - darwin_amd64

brews:
  -
    name: 'svt'
    homepage: 'https://github.com/permafrost-dev/svt'
    description: 'semantic version tools'
    license: "MIT"
    tap:
      owner: 'permafrost-dev'
      name: homebrew-svt
      branch: main

checksum:
  name_template: "checksums.txt"
  algorithm: sha256
